//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduPointStudApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lasnaolotiedot
    {
        public Nullable<System.DateTime> KirjattuSisaan { get; set; }
        public Nullable<System.DateTime> KirjattuUlos { get; set; }
        public string Luokkakoodi { get; set; }
        public Nullable<int> OpettajaID { get; set; }
        public int RekisteriID { get; set; }
        public Nullable<int> OpiskelijaID { get; set; }
        public Nullable<int> KurssiID { get; set; }
        public Nullable<int> LuokkaID { get; set; }
        public Nullable<int> KirjattuID { get; set; }
    
        public virtual Kurssi Kurssi { get; set; }
        public virtual Opettaja Opettaja { get; set; }
        public virtual Opiskelija Opiskelija { get; set; }
        public virtual Luokkahuone Luokkahuone { get; set; }
    }
}
