//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduPointStudApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opettaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opettaja()
        {
            this.Lasnaolotiedot = new HashSet<Lasnaolotiedot>();
        }
    
        public int OpettajaID { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Opettajanro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lasnaolotiedot> Lasnaolotiedot { get; set; }
    }
}
