//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduPointStudApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opiskelija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opiskelija()
        {
            this.Lasnaolotiedot = new HashSet<Lasnaolotiedot>();
        }
    
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Opiskelijanro { get; set; }
        public int OpiskelijaID { get; set; }
        public string Tutkinto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lasnaolotiedot> Lasnaolotiedot { get; set; }
    }
}
